### PR TITLE
Team 2 shylan21 error messages styling

### PR DESCRIPTION
**Pull request by Shylan21**

### CODE REVIEW

**Review by ManNavic — DISMISSED** [review]
LGTM

**Comment by dearshrewdwit** [comment]
[Registration - consistent error message styling](https://trello.com/c/wLgyEXNF/23-registration-consistent-error-message-styling)

**Comment by procrastian** [comment]
just the conflicts to resolve once Mantas' registration is approved

**Review by dearshrewdwit — APPROVED** [review]

**Review by procrastian — APPROVED** [review]
LGTM!

**Pull request merged**
